import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({children}: Readonly<{children: React.ReactNode}>) => {
  return (
    <html lang="ja">
      <body className={"min-h-dvh"}>
        <main className={"flex"}>
          {children}
        </main>
      </body>
    </html>
  );
}

export default RootLayout;